pretrained_t2v_model_path: "./checkpoints/zeroscope_v2_576w"
pretrained_lora_model_path: "./checkpoints/stive/car-turn"
pretrained_concepts_model_path: "./checkpoints/concepts/vehicles-subset"
output_dir: ".log/ptp/car-turn/base/"
checkpoints_dir: "checkpoints/ptp/car-turn/"

validation_data:
  source: "data/targets/videos/car-turn.mp4"
  source_prompt: "a jeep driving down a curvy road in the countryside."
  edit_prompts:
    - "a car driving down a curvy road in the countryside."
  num_frames: 8
  sample_stride: 1
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 34
  guidance_scale: 7.5
  use_inv_latent: True
  num_inv_steps: 34

ptp_conf:
  is_replace_controller: True
  cross_replace_steps: [0.2, 1.0]
  self_replace_steps: [0.2, 1.0]
  blend_words: 
    sources:
      - "jeep"
    targets:
      - "car"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.3, 0.3]

seed: 33
mixed_precision: 'fp16'
# mixed_precision: 'no'
