pretrained_t2v_model_path: "./checkpoints/zeroscope_v2_576w"
pretrained_lora_model_path: "./checkpoints/stive/lambo"
pretrained_concepts_model_path: "./checkpoints/concepts/lambo"
output_dir: ".log/ptp/car-turn/to-lambo/"
checkpoints_dir: "checkpoints/ptp/car-turn/to-lambo"

validation_data:
  source: "data/targets/car-turn/videos/car-turn.mp4"
  source_prompt: "a jeep driving down a curvy road in the countryside"
  # source_prompt: "a jeep driving on the road"

  edit_prompts:
    - "a $LAMBO driving down a curvy road in the countryside"
    # - "a $LAMBO driving on the road"
    # - "a car driving on the road"
  num_frames: 4
  sample_stride: 1
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 30
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 30

ptp_conf:
  source_mask: "data/targets/car-turn/check/car-turn_jeep_frame_masks.mp4"
  is_replace_controller: True
  cross_replace_steps: [0.0, 0.5]
  self_replace_steps: [0.0, 0.1]
  blend_words: 
    sources:
      - "jeep"
    targets:
      - "$LAMBO"
      # - "car"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.3, 0.3]
  fuse_th: 0.01
  # fuse_scale: 1.5

seed: 33
mixed_precision: 'fp16'
