pretrained_t2v_model_path: "./checkpoints/zeroscope_v2_576w"
pretrained_concepts_model_path: "./checkpoints/concepts/vehicles-subset"
output_dir: ".log/ptp/vehicles-subset/base/"
checkpoints_dir: "checkpoints/ptp/vehicles-subset/"

validation_data:
  source: "data/targets/videos/car-turn.mp4"
  source_prompt: "a $JEEP is moving on the road."
  edit_prompts:
    - "a $FERRARI is moving on the road."
  num_frames: 8
  sample_stride: 1
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

ptp_conf:
  is_replace_controller: True
  cross_replace_steps: [0.5, 1.0]
  self_replace_steps: [0.5, 1.0]
  blend_words: 
    sources:
      - "$JEEP"
    targets:
      - "$FERRARI"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.3, 0.3]

seed: 33
mixed_precision: 'fp16'
# mixed_precision: 'no'
