pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
pretrained_concepts_model_path: "./checkpoints/sd_concepts/frenchflag"
output_dir: ".log/sd_unet/frenchflag/base/"
checkpoints_dir: "checkpoints/sd_unet/frenchflag"

train_data:
  video_paths:
    - "data/targets/usa-flag/videos/usa-flag.mp4"
  prompts:
    - "a American flag on a flagpole moves in the wind"
  mask_paths:
    - "data/targets/usa-flag/masks/usa-flag_flag_frame_masks.mp4"
  num_frames: 6
  sample_stride: 6
  width: 512
  height: 512
  rand_slice: False
  target_video_paths:
    - "data/targets/usa-flag/videos/usa-flag.mp4"
  target_mask_paths:
    - "data/targets/usa-flag/masks/usa-flag_flag_frame_masks.mp4"
  target_prompts:
    - "a French flag on a flagpole moves in the wind"

validation_data:
  source: "data/targets/usa-flag/videos/usa-flag.mp4"
  source_prompt: "a American flag on a flagpole moves in the wind"
  edit_prompts:
    - "a French flag on a flagpole moves in the wind"
  num_frames: 6
  sample_stride: 6
  width: 512
  height: 512
  replace_indices: [[2]]    # American -> 'French'

extra_trainable_modules:
  - "^.*\\.attentions\\..*\\.attn1\\.to_q\\..*$"
  - "^.*\\.attentions\\..*\\.attn2\\.to_q\\..*$"
  - "^.*\\.temp_lora_conv\\..*"
  - "^.*\\.attentions\\..*\\.attn_temp\\..*$"

inference_conf:
  num_inference_steps: 30
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 30

# CHECK
sub_sot: True
cam_loss_type: 'mae'
unet_begin_store_idx: 0
enable_scam_loss: True
scam_weight: 0.1
scam_only_neg: True
enable_tcam_loss: True
tcam_only_neg: True
tcam_weight: 0.1
cam_loss_reduction: 'mean'
attn_check_steps: 15

learning_rate: 1.0e-5
batch_size: 1
num_train_epoch: 50
checkpointing_steps: 2000
validation_steps: 5

seed: 33
mixed_precision: 'fp16'
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
enable_torch_2_attn: True
gradient_accumulation_steps: 1
