pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: ".log/tive/loveu-tgve/no-abstract/"

train_data:
  data_dir: "data/loveu-tgve/videos"
  csv_file: "data/loveu-tgve/LOVEU-TGVE-Abstracts-Prompts.csv"
  width: 512
  height: 512
  num_frames: 4
  sample_stride: 1
  rand_slice: False
  abstracts_prompt: True

validation_data:
  sources: 
    - "data/custom/videos/car-turn.mp4"
    - "data/custom/videos/cybertrunk.mp4"
    - "data/custom/videos/tesla.mp4"
  prompts:
    - "a $JEEP is $TURNING on the road with the background of $MOUNTAINS."
    - "a $CYBERTRUNK is $MOVING along a road through the $FOREST."
    - "a $TESLA is $DRIFTING on the $SNOW."
  num_frames: 12
  sample_stride: 1
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

abstracts_file: "data/loveu-tgve/abstracts.json"
max_temporal_steps: 12
learning_rate: 3e-5
batch_size: 1
num_train_epoch: 200
checkpointing_steps: 1000
validation_steps: 200

trainable_modules:
  - "tp_blocks"
  - "attn1.primary_lin"
  - "attn1.comp_q"
  - "attn1.comp_out"
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
