pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
pretrained_lora_model_path: "./checkpoints/sd_unet/ogfootball"
pretrained_concepts_model_path: "./checkpoints/sd_concepts/ogfootball"
output_dir: ".log/ptp/sd_ptp/steel/to-ogfootball/"
checkpoints_dir: "checkpoints/sd_ptp/steel/to-ogfootball"

validation_data:
  source: "data/targets/steel/videos/steel.mp4"
  source_prompt: "four ball on a wooden table"
  edit_prompts:
    - "four $OGFOOTBALL on a wooden table"
  num_frames: 6
  sample_stride: 6
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 35
  guidance_scale: 15
  use_inv_latent: True
  num_inv_steps: 35

ptp_conf:
  source_mask: "data/targets/steel/check/steel_ball_frame_masks.mp4"
  is_replace_controller: True
  cross_replace_steps: [0.0, 0.8]
  self_replace_steps: [0.0, 0.8]
  blend_words: 
    sources:
      - "ball"
    targets:
      - "$OGFOOTBALL"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.3, 0.3]
  fuse_th: 0.01

seed: 33
mixed_precision: 'fp16'
