pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
pretrained_lora_model_path: "./checkpoints/sd_unet/tesla/ferrari"
pretrained_concepts_model_path: "./checkpoints/sd_concepts/ferrari"
output_dir: ".log/ptp/sd_tesla/to-ferrari/"
checkpoints_dir: "checkpoints/sd_ptp/tesla/to-ferrari"

validation_data:
  source: "data/targets/tesla/videos/tesla.mp4"
  source_prompt: "a car is drifting in the snow"

  edit_prompts:
    - "a $FERRARI is drifting in the snow"
  num_frames: 6
  sample_stride: 8
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 35
  guidance_scale: 10.5
  use_inv_latent: True
  num_inv_steps: 35

ptp_conf:
  source_mask: "data/targets/tesla/check/tesla_car_frame_masks.mp4"
  is_replace_controller: True
  cross_replace_steps: [0.0, 0.3]
  self_replace_steps: [0.0, 0.3]
  blend_words: 
    sources:
      - "car"
    targets:
      - "$FERRARI"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.2, 0.2]
  fuse_th: 0.01
  # fuse_scale: 1.5

seed: 33
mixed_precision: 'fp16'
