pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
pretrained_lora_model_path: "./checkpoints/sd_unet/car-drift/to-lambo"
pretrained_concepts_model_path: "./checkpoints/sd_concepts/lambo"
output_dir: ".log/ptp/sd_car-drift/to-lambo/"
checkpoints_dir: "checkpoints/sd_ptp/car-drift/to-lambo"

validation_data:
  source: "data/targets/car-drift/videos/car-drift.mp4"
  source_prompt: "a car drifting around the road sign"
  edit_prompts:
    - "a $LAMBO drifting around the road sign"
  num_frames: 6
  sample_stride: 6
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 35
  guidance_scale: 15
  use_inv_latent: True
  num_inv_steps: 35

ptp_conf:
  source_mask: "data/targets/car-drift/check/car-drift_jeep_frame_masks.mp4"
  is_replace_controller: True
  cross_replace_steps: [0.0, 0.3]
  self_replace_steps: [0.0, 0.3]
  blend_words: 
    sources:
      - "car"
    targets:
      - "$LAMBO"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.3, 0.3]
  fuse_th: 0.01

seed: 33
mixed_precision: 'fp16'
