pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
pretrained_lora_model_path: "./checkpoints/sd_unet/car-drift/gt3"
pretrained_concepts_model_path: "./checkpoints/sd_concepts/gt3"
output_dir: ".log/ptp/sd_car-drift/to-gt3/"
checkpoints_dir: "checkpoints/sd_ptp/car-drift/to-gt3"

validation_data:
  source: "data/targets/car-drift/videos/car-drift.mp4"
  source_prompt: "a car is drifting around a curve road with the background of a forest"

  edit_prompts:
    - "a $GT3 is drifting around a curve road with the background of a forest"
  num_frames: 6
  sample_stride: 8
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 37
  guidance_scale: 7.5
  use_inv_latent: True
  num_inv_steps: 37

ptp_conf:
  source_mask: "data/targets/car-drift/check/car-drift_car_frame_masks.mp4"
  is_replace_controller: True
  cross_replace_steps: [0.0, 0.0]
  self_replace_steps: [0.0, 0.0]
  blend_words: 
    sources:
      - "car"
    targets:
      - "$GT3"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.3, 0.3]
  fuse_th: 0.01

seed: 33
mixed_precision: 'fp16'
