pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
pretrained_concepts_model_path: "./checkpoints/sd_concepts/audi"
output_dir: ".log/sd_unet/race/base/"
checkpoints_dir: "checkpoints/sd_unet/audi"

train_data:
  video_paths:
    - "data/targets/race/videos/race.mp4"
    - "data/concepts/audi/videos/audi.mp4"
  prompts:
    - "a car is drifting on the race track"
    - "a $AUDI driving along a road"
  mask_paths:
    - "data/targets/race/masks/race_car_frame_masks.mp4"
    - "data/concepts/audi/masks/audi_car_frame_masks.mp4"
  enable_temporal_modules:
    - True
    - True
  num_frames: 6
  sample_stride: 8
  width: 512
  height: 512
  rand_slice: False
  target_video_paths:
    - "data/targets/race/videos/race.mp4"
  target_mask_paths:
    - "data/targets/race/masks/race_car_frame_masks.mp4"
  target_prompts:
    - "a $AUDI is drifting on the race track"

validation_data:
  source: "data/targets/race/videos/race.mp4"
  source_prompt: "a car is drifting on the race track"
  edit_prompts:
    - "a $AUDI is drifting on the race track"
  num_frames: 6
  sample_stride: 8
  width: 512
  height: 512
  replace_indices: [[2]]    # car -> '$AUDI'

extra_trainable_modules:
  - "^.*\\.attentions\\..*\\.attn1\\.to_q\\..*$"
  - "^.*\\.attentions\\..*\\.attn2\\.to_q\\..*$"
  - "^.*\\.temp_lora_conv\\..*"
  - "^.*\\.attentions\\..*\\.attn_temp\\..*$"

inference_conf:
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

# CHECK
sub_sot: True
cam_loss_type: 'mae'
unet_begin_store_idx: 0
enable_scam_loss: True
scam_weight: 0.1
scam_only_neg: True
enable_tcam_loss: True
tcam_only_neg: True
tcam_weight: 0.1
cam_loss_reduction: 'mean'
attn_check_steps: 15

learning_rate: 1.0e-5
batch_size: 1
num_train_epoch: 100
checkpointing_steps: 2000
validation_steps: 10

seed: 33
mixed_precision: 'fp16'
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
enable_torch_2_attn: True
gradient_accumulation_steps: 1
