pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
pretrained_lora_model_path: "./checkpoints/sd_unet/cat"
pretrained_concepts_model_path: "./checkpoints/sd_concepts/cat"
output_dir: ".log/ptp/gray-dog/to-cat/"
checkpoints_dir: "checkpoints/sd_ptp/gray-dog/to-cat"

validation_data:
  source: "data/targets/gray-dog/videos/gray-dog.mp4"
  source_prompt: "a dog sitting on the mat"

  edit_prompts:
    - "a $CAT sitting on the mat"
  num_frames: 6
  sample_stride: 6
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 33
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 33

ptp_conf:
  source_mask: "data/targets/gray-dog/videos/gray-dog_dog_frame_masks.mp4"
  # is_replace_controller: False
  is_replace_controller: True
  cross_replace_steps: [0.0, 0.3]
  self_replace_steps: [0.0, 0.3]
  blend_words: 
    sources:
      - "dog"
    targets:
      - "$CAT"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.3, 0.3]
  fuse_th: 0.01
  # fuse_scale: 1.5

seed: 33
mixed_precision: 'fp16'
