pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
pretrained_lora_model_path: "./checkpoints/sd_unet/fox"
pretrained_concepts_model_path: "./checkpoints/sd_concepts/fox"
output_dir: ".log/ptp/sd_fox/to-fox/"
checkpoints_dir: "checkpoints/sd_ptp/gray-dog/to-fox"

validation_data:
  source: "data/targets/gray-dog/videos/gray-dog.mp4"
  source_prompt: "a dog sitting on a mat"

  edit_prompts:
    - "a $FOX sitting on a mat"
  num_frames: 6
  sample_stride: 8
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 40
  guidance_scale: 7.5
  use_inv_latent: True
  num_inv_steps: 40

ptp_conf:
  source_mask: "data/targets/gray-dog/check/gray-dog_dog_frame_masks.mp4"
  # is_replace_controller: True
  is_replace_controller: False
  cross_replace_steps: [0.0, 0.3]
  self_replace_steps: [0.0, 0.3]
  blend_words: 
    sources:
      - "dog"
    targets:
      - "$FOX"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.3, 0.3]
  fuse_th: 0.01

seed: 33
mixed_precision: 'fp16'
