pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: ".log/sd_concepts/neo/base/"
checkpoints_dir: "checkpoints/sd_concepts/neo"

train_data:
  video_paths: 
    - "data/concepts/neo/videos/neo.mp4"
  prompts: 
    - "$NEO"
  mask_paths:
    - "data/concepts/neo/masks/neo_car_frame_masks.mp4"
  width: 512
  height: 512
  num_frames: 6
  # sample_stride: 1
  enable_slice: True
  rand_slice: True
  rand_slice_length: True
  rand_slice_stride: True
  relax_mask: False
  target_video_paths: 
    - "data/targets/man-skate/videos/man-skate.mp4"
  target_mask_paths: 
    - "data/targets/man-skate/masks/man-skate_jeep_frame_masks.mp4"
  target_prompts:
    - "a $NEO driving down a curvy road in the countryside"
  enable_target_slice: True
  target_rand_slice: True
  target_rand_slice_length: True
  target_rand_slice_stride: True
  relax_target_mask: False

validation_data:
  sources:
    - "data/concepts/neo/videos/neo.mp4"
    - "data/targets/man-skate/videos/man-skate.mp4"
  prompts:
    - "a $NEO moving along a road"
    - "a $NEO driving down a curvy road in the countryside"
  num_frames: 6
  sample_stride: 6
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

enable_prefix: True
concepts: ['$NEO']
concepts_num_embedding: 1
retain_position_embedding: True

sub_sot: True
cam_loss_type: 'mae'
unet_begin_store_idx: 0
enable_scam_loss: True
scam_weight: 0.0
scam_only_neg: True

enable_tcam_loss: True
tcam_weight: 0.0
tcam_only_neg: True
cam_loss_reduction: 'mean'
attn_check_steps: 500

learning_rate: 5.0e-4
batch_size: 1
num_train_epoch: 7000
checkpointing_steps: 20000
validation_steps: 500

seed: 33
mixed_precision: 'fp16'
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
enable_torch_2_attn: True
gradient_accumulation_steps: 1
