pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: ".log/sd_concepts/rhino/base/"
checkpoints_dir: "checkpoints/sd_concepts/rhino"

train_data:
  video_paths: 
    - "data/concepts/rhino/videos/rhino.mp4"
  prompts: 
    - "a $RHINO walking on the rock against a wall"
  mask_paths:
    - "data/concepts/rhino/masks/rhino_rhino_frame_masks.mp4"
  width: 512
  height: 512
  num_frames: 8
  enable_slice: True
  rand_slice: True
  rand_slice_length: True
  rand_slice_stride: True
  relax_mask: 0

validation_data:
  sources:
    - "data/concepts/rhino/videos/rhino.mp4"
    - "data/targets/bear/videos/bear.mp4"
  prompts:
    - "a $RHINO is walking near a pile of rocks and a forest"
    - "a $RHINO walking on the rock against a wall"
  num_frames: 6
  sample_stride: 8
  width: 512
  height: 512
  
inference_conf:
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

enable_prefix: True
concepts: ['$RHINO']
concepts_num_embedding: 1
retain_position_embedding: True

lora_conf:
  r: 16
  lora_alpha: 1.0
  lora_dropout: 0.1
  target_modules:
    - "^.*\\.attentions\\..*\\.attn2\\.to_v\\..*$"
  bias: "none"
lora_lr: 1.0e-5

sub_sot: True
cam_loss_type: 'mae'
unet_begin_store_idx: 0
enable_scam_loss: False
scam_weight: 0.0
scam_only_neg: True

enable_tcam_loss: False
tcam_weight: 0.0
tcam_only_neg: True
cam_loss_reduction: 'mean'
attn_check_steps: 500

learning_rate: 1.0e-3
batch_size: 1
num_train_epoch: 3500
checkpointing_steps: 20000
validation_steps: 500

seed: 33
mixed_precision: 'fp16'
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
enable_torch_2_attn: True
gradient_accumulation_steps: 1
