pretrained_zs_model_path: "./checkpoints/zeroscope_v2_576w"
output_dir: ".log/zs_concepts/ferrari/base/"
checkpoints_dir: "checkpoints/zs_concepts/ferrari"

train_data:
  video_paths: 
    - "data/concepts/ferrari/videos/ferrari.mp4"
  prompts: 
    - "a $FERRARI is driving through the forest"
  mask_paths:
    - "data/concepts/ferrari/masks/ferrari_car_frame_masks.mp4"
  width: 384
  height: 384
  num_frames: 8
  # sample_stride: 4
  enable_slice: True
  rand_slice: True
  rand_slice_length: True
  rand_slice_stride: True
  relax_mask: False
  target_video_paths: 
    - "data/targets/car-turn/videos/car-turn.mp4"
  target_mask_paths: 
    - "data/targets/car-turn/masks/car-turn_jeep_frame_masks.mp4"
  target_prompts:
    - "a $FERRARI driving down a curvy road in the countryside"
  enable_target_slice: False
  target_rand_slice: True
  target_rand_slice_length: True
  target_rand_slice_stride: True
  relax_target_mask: False

validation_data:
  sources:
    - "data/concepts/ferrari/videos/ferrari.mp4"
    - "data/targets/car-turn/videos/car-turn.mp4"
  prompts:
    - "a $FERRARI is driving through the forest"
    - "a $FERRARI driving down a curvy road in the countryside"
  num_frames: 6
  sample_stride: 6
  width: 384
  height: 384

inference_conf:
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

enable_prefix: False
concepts: ['$FERRARI']
concepts_num_embedding: 1
retain_position_embedding: True


sub_sot: True
cam_loss_type: 'mae'
unet_begin_store_idx: 0
enable_scam_loss: True
scam_weight: 0.0
scam_only_neg: False

enable_tcam_loss: True
tcam_weight: 0.0
tcam_only_neg: True
cam_loss_reduction: 'mean'
attn_check_steps: 10

learning_rate: 5.0e-4
batch_size: 1
num_train_epoch: 5000
checkpointing_steps: 5000
validation_steps: 50

seed: 33
mixed_precision: 'fp16'
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
enable_torch_2_attn: True
gradient_accumulation_steps: 1
