pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: ".log/abstracts_clip/one-shot/cybertrunk/base/"
checkpoints_dir: "checkpoints/abstracts_clip/one-shot/cybertrunk/"

train_data:
  data_dir: "data/one-shot/cybertrunk/"
  width: 512
  height: 512
  num_frames: 6
  sample_stride: 1
  rand_slice: False

validation_data:
  sources: 
    - "data/one-shot/cybertrunk/videos/cybertrunk.mp4"
    - "data/one-shot/cybertrunk/videos/cybertrunk.mp4"
    - "data/one-shot/cybertrunk/videos/cybertrunk.mp4"
    - "data/one-shot/cybertrunk/videos/cybertrunk.mp4"
  prompts:
    - "a jeep car is driving through the forest"
    - "a $CYBERTRUNK is driving on the beach."
    - "a $CYBERTRUNK is driving in the snow."
    - "a $CYBERTRUNK is driving on the road, cartoon style."

  num_frames: 6
  sample_stride: 1
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

abstracts_file: "data/one-shot/cybertrunk/abstracts.json"
abstracts_num_embedding: 1
attention_mask_one_hot: True
retain_position_embedding: True
learning_rate: 5.0e-3
batch_size: 1
num_train_epoch: 1000
checkpointing_steps: 1000
validation_steps: 50

seed: 33
# mixed_precision: fp16
mixed_precision: "no"
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
