pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: ".log/tive/loveu-tgve/no-abstract/"

train_data:
  data_dir: "data/loveu-tgve/videos"
  csv_file: "data/loveu-tgve/LOVEU-TGVE-Abstracts-Prompts.csv"
  width: 512
  height: 512
  num_frames: 4
  sample_stride: 1
  rand_slice: False
  abstracts_prompt: True

validation_data:
  sources: 
    - "data/loveu-tgve/videos/aircraft-landing.mp4"
    - "data/loveu-tgve/videos/aircraft-landing.mp4"
    - "data/loveu-tgve/videos/cat-in-the-sun.mp4"
    - "data/loveu-tgve/videos/cat-in-the-sun.mp4"
    - "data/loveu-tgve/videos/eiffel-flyover.mp4"
    - "data/loveu-tgve/videos/eiffel-flyover.mp4"
  prompts:
    - "A $DETLAAIRCRAFT descends onto the runaway during a $CLOUDLESS morning with a blue $SKY in the background."
    - "A $DETLAAIRCRAFT descends onto the runaway during $SUNSET with an orange $SKY in the background."
    - "A $GINGER cat in the $GRASSLAND on a $SUNNY day in the background."
    - "A $GINGER cat in the $GRASSLAND on with a blue $SKY in the background."
    - "Drone flyover of the Eiffel Tower in front of the city during $SUNSET in the background."
    - "Drone flyover of the Eiffel Tower in front of the city in the style of $FIREWORKS."
  num_frames: 12
  sample_stride: 1
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

abstracts_file: "data/loveu-tgve/abstracts.json"
abstracts_num_embedding: 2
max_temporal_steps: 12
learning_rate: 3e-5
batch_size: 1
num_train_epoch: 200
checkpointing_steps: 1000
validation_steps: 200

trainable_modules:
  - "tp_blocks"
  - "attn1.primary_lin"
  - "attn1.comp_q"
  - "attn1.comp_out"
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
