pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: ".log/tp_tive/one-shot/cat-in-the-sun/base/"

train_data:
  data_dir: "data/one-shot/cat-in-the-sun/videos"
  csv_file: "data/one-shot/cat-in-the-sun/one-shot.csv"
  width: 512
  height: 512
  num_frames: 6
  sample_stride: 1
  rand_slice: False
  abstracts_prompt: True

validation_data:
  sources: 
    - "data/one-shot/cat-in-the-sun/videos/cat-in-the-sun.mp4"
    - "data/one-shot/cat-in-the-sun/videos/cat-in-the-sun.mp4"
  prompts:
    - "A $CAT sits in the grassland on a sunny day."
    - "A $CAT sits in the grassland on a snowy day."

  num_frames: 6
  sample_stride: 1
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

abstracts_file: "data/one-shot/cat-in-the-sun/abstracts.json"
abstracts_num_embedding: 1
max_temporal_steps: 12
learning_rate: 3.0e-5
batch_size: 1
num_train_epoch: 250
checkpointing_steps: 100
validation_steps: 50

trainable_modules:
  - "tp_blocks"
  - "attn1.primary_lin"
  - "attn1.comp_q"
  - "attn1.comp_out"
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
