pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
pretrained_lora_model_path: "./checkpoints/sd_unet/kitten/tiger"
output_dir: ".log/ptp/sd_tiger/to-tiger/"
checkpoints_dir: "checkpoints/sd_ptp/kitten/to-tiger"

validation_data:
  source: "data/targets/kitten/videos/kitten.mp4"
  source_prompt: "a black cat walking on the floor next to a wall"

  edit_prompts:
    - "a red tiger walking on the floor next to a wall"
  num_frames: 6
  sample_stride: 8
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 37
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 37

ptp_conf:
  source_mask: "data/targets/kitten/check/kitten_cat_frame_masks.mp4"
  is_replace_controller: True
  cross_replace_steps: [0.0, 0.4]
  self_replace_steps: [0.0, 0.4]
  blend_words: 
    sources:
      - "black"
      - "cat"
    targets:
      - "red"
      - "tiger"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.3, 0.3]
  fuse_th: 0.01

seed: 33
mixed_precision: 'fp16'
