pretrained_t2v_model_path: "./checkpoints/zeroscope_v2_576w"
pretrained_concepts_model_path: "./checkpoints/concepts/porche"
output_dir: ".log/stive/porche/base/"
checkpoints_dir: "checkpoints/stive/porche/"

train_data:
  sources:
    - "data/concepts/porche/videos/car-turn.mp4"
  prompts:
    - "a jeep driving down a curvy road in the countryside"
  num_frames: 8
  sample_stride: 1
  width: 512
  height: 512
  rand_slice: True

validation_data:
  source: "data/concepts/ferrari/videos/car-turn.mp4"
  source_prompt: "a jeep driving down a curvy road in the countryside"
  edit_prompts:
    - "a jeep driving down a curvy road in the countryside"
    - "a car driving down a curvy road in the countryside"
  num_frames: 8
  sample_stride: 1
  width: 512
  height: 512

lora_conf:
  r: 6
  lora_alpha: 1.0
  lora_dropout: 0.1
  target_modules:
    - "^.*\\.attentions\\..*\\.attn1\\.to_q\\..*$"
    - "^.*\\.attentions\\..*\\.attn2\\.to_q\\..*$"
    # - "^.*\\.attentions\\..*\\.attn2\\.to_v\\..*$"
    # - "^.*\\.attentions\\..*\\.ff\\.net\\.2\\..*$"
  bias: "none"

# extra_trainable_modules:
#   - "^.*\\.attentions\\..*\\.attn1\\.to_q\\..*$"
#   - "^.*\\.attentions\\..*\\.attn2\\.to_q\\..*$"

inference_conf:
  num_inference_steps: 30
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 30

learning_rate: 1.0e-5
batch_size: 1
num_train_epoch: 50
checkpointing_steps: 2000
validation_steps: 10

seed: 33
mixed_precision: 'fp16'
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
enable_torch_2_attn: True
gradient_accumulation_steps: 1
