pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
pretrained_lora_model_path: "./checkpoints/sd_unet/frenchflag"
pretrained_concepts_model_path: "./checkpoints/sd_concepts/frenchflag"
output_dir: ".log/ptp/usa-flag/to-frenchflag/"
checkpoints_dir: "checkpoints/sd_ptp/usa-flag/to-frenchflag"

validation_data:
  source: "data/targets/usa-flag/videos/usa-flag.mp4"
  source_prompt: "a American flag on a flagpole moves in the windd"

  edit_prompts:
    - "a French flag on a flagpole moves in the wind"
  num_frames: 6
  sample_stride: 6
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 33
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 33

ptp_conf:
  source_mask: "data/targets/usa-flag/videos/usa-flag_flag_frame_masks.mp4"
  # is_replace_controller: True
  is_replace_controller: False
  cross_replace_steps: [0.0, 0.1]
  self_replace_steps: [0.0, 0.1]
  blend_words: 
    sources:
      - "American"
    # targets:
    #   - "French"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.3, 0.3]
  fuse_th: 0.01
  # fuse_scale: 1.5

seed: 33
mixed_precision: 'fp16'
