pretrained_sd_model_path: "./checkpoints/stable-diffusion-v1-4"
pretrained_lora_model_path: "./checkpoints/sd_unet/tennis/ultron"
pretrained_concepts_model_path: "./checkpoints/sd_concepts/ultron"
output_dir: ".log/ptp/tennis/to-ultron/"
checkpoints_dir: "checkpoints/sd_ptp/tennis/to-ultron"

validation_data:
  source: "data/targets/tennis/videos/tennis.mp4"
  source_prompt: "a man playing tennis on the red ground"
  edit_prompts:
    - "a $ULTRON playing tennis on the red ground"
  num_frames: 6
  sample_stride: 3
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 40
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 40

ptp_conf:
  source_mask: "data/targets/tennis/videos/tennis_man_frame_masks.mp4"
  # is_replace_controller: False
  is_replace_controller: True
  cross_replace_steps: [0.0, 0.1]
  self_replace_steps: [0.0, 0.1]
  blend_words: 
    sources:
      - "man"
    targets:
      - "$ULTRON"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0., 0.]
  fuse_th: 0.01
  # fuse_scale: 1.5

seed: 33
mixed_precision: 'fp16'
