pretrained_t2v_model_path: "./checkpoints/zeroscope_v2_576w"
output_dir: ".log/concepts/ferrari/base/"
checkpoints_dir: "checkpoints/concepts/ferrari"

train_data:
  video_paths: 
    - "data/concepts/ferrari/videos/ferrari.mp4"
  prompts: 
    - "a $FERRARI is driving along a road"
  mask_paths:
    - "data/concepts/ferrari/masks/ferrari_car_frame_masks.mp4"
  width: 512
  height: 512
  num_frames: 4
  sample_stride: 1
  rand_slice: False
  target_video_paths: 
    - "data/targets/car-turn/videos/car-turn.mp4"
  target_mask_paths: 
    - "data/targets/car-turn/masks/car-turn_jeep_frame_masks.mp4"
  target_prompts:
    - "a $FERRARI driving down a curvy road in the countryside"

validation_data:
  sources:
    - "data/concepts/ferrari/videos/ferrari.mp4"
    - "data/targets/car-turn/videos/car-turn.mp4"
  prompts:
    - "a $FERRARI is driving along a road"
    - "a $FERRARI driving down a curvy road in the countryside"
  num_frames: 4
  sample_stride: 1
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 30
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 30

concepts: ['$FERRARI']
pseudo_words: ['car']
concepts_num_embedding: 1
retain_position_embedding: True


# sub_sot: True
# cam_loss_type: 'mae'
# enable_scam_loss: True
# scam_weight: 1.0e-1
# enable_tcam_loss: True
# tcam_weight: 1.0e-1
# attn_check_steps: 10

# # CHECK
# sub_sot: True
# cam_loss_type: 'mae'
# enable_scam_loss: True
# scam_weight: 0.0
# enable_tcam_loss: True
# tcam_weight: 0.0
# attn_check_steps: 10

# ONLY SCAM
sub_sot: True
cam_loss_type: 'mae'

enable_scam_loss: True
scam_weight: 0.1
scam_only_neg: False

enable_tcam_loss: True
tcam_weight: 0.1
tcam_only_neg: True
cam_loss_reduction: 'mean'
attn_check_steps: 10


learning_rate: 3.0e-3
batch_size: 1
num_train_epoch: 2000
checkpointing_steps: 5000
validation_steps: 50

seed: 33
mixed_precision: 'fp16'
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
enable_torch_2_attn: True
gradient_accumulation_steps: 1
