pretrained_t2v_model_path: "./checkpoints/zeroscope_v2_576w"
output_dir: ".log/concepts/ferrari/base/"
checkpoints_dir: "checkpoints/concepts/ferrari/"

train_data:
  data_dir: "data/concepts/ferrari/"
  width: 512
  height: 512
  num_frames: 8
  sample_stride: 1
  rand_slice: True
  concepts_prompt: True

validation_data:
  sources:
    - "data/concepts/ferrari/videos/car-turn.mp4"
  prompts:
    - "a $FERRARI driving down a curvy road in the countryside."
  num_frames: 8
  sample_stride: 1
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 30
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 30

concepts_file: "data/concepts/ferrari/concepts.json"
learning_rate: 5.0e-3
batch_size: 1
num_train_epoch: 300
checkpointing_steps: 1000
validation_steps: 50

seed: 33
mixed_precision: 'fp16'
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
enable_torch_2_attn: True
gradient_accumulation_steps: 1
