pretrained_t2v_model_path: "./checkpoints/zeroscope_v2_576w"
output_dir: ".log/concepts/ferrari/base/"
checkpoints_dir: "checkpoints/concepts/lambo/"

train_data:
  data_dir: "data/concepts/lambo/"
  width: 512
  height: 512
  num_frames: 8
  sample_stride: 1
  rand_slice: True
  concepts_prompt: True
  target_video_path: "data/targets/car-turn/videos/car-turn.mp4"
  target_mask_path: "data/targets/car-turn/masks/car-turn_jeep_frame_masks.mp4"

concepts_file: "data/concepts/lambo/concepts.json"
validation_data:
  sources:
    - "data/targets/car-turn/videos/car-turn.mp4"
  prompts:
    - "a $LAMBO driving down a curvy road in the countryside"
  num_frames: 8
  sample_stride: 1
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 30
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 30

use_attn_mask_loss: False
attn_mask_weight: 1.0e-1
learning_rate: 1.0e-3
batch_size: 1
num_train_epoch: 500
checkpointing_steps: 1000
validation_steps: 50

seed: 33
mixed_precision: 'fp16'
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
enable_torch_2_attn: True
gradient_accumulation_steps: 1
