pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: ".log/vae3d/loveu-tgve/"

eval_data:
  data_dir: "data/loveu-tgve/videos"
  csv_file: "data/loveu-tgve/LOVEU-TGVE-2023_Dataset.csv"
  width: 512
  height: 512
  num_frames: 12
  sample_stride: 1

batch_size: 1
st_insertion_up_block_ids: [0]
seed: 33
mixed_precision: fp16
# gradient_checkpointing: True