pretrained_t2v_model_path: "./checkpoints/zeroscope_v2_576w"
pretrained_lora_model_path: "./checkpoints/stive/porche"
pretrained_concepts_model_path: "./checkpoints/concepts/porche"
output_dir: ".log/ptp/car-turn/to-porche/"
checkpoints_dir: "checkpoints/ptp/car-turn/to-porche"

validation_data:
  source: "data/targets/videos/car-turn.mp4"
  source_prompt: "a jeep driving down a curvy road in the countryside"
  edit_prompts:
    - "a car driving down a curvy road in the countryside"
  num_frames: 8
  sample_stride: 1
  width: 512
  height: 512

inference_conf:
  num_inference_steps: 30
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 30

ptp_conf:
  is_replace_controller: True
  cross_replace_steps: [0.0, 0.5]
  self_replace_steps: [0.0, 0.5]
  blend_words: 
    sources:
      - "jeep"
    targets:
      - "car"
  blend_self_attention: True
  use_inversion_attention: True
  blend_th: [0.5, 0.5]
  fuse_th: 0.0

seed: 33
mixed_precision: 'fp16'
