pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: ".log/abstract_clip/one-shot/ski-lift-time-lapse/base/"

train_data:
  data_dir: "data/one-shot/ski-lift-time-lapse/videos"
  csv_file: "data/one-shot/ski-lift-time-lapse/one-shot.csv"
  width: 512
  height: 512
  num_frames: 6
  sample_stride: 1
  rand_slice: False
  abstracts_prompt: True

abstracts_file: "data/one-shot/ski-lift-time-lapse/abstracts.json"
abstracts_num_embedding: 1
retain_position_embedding: True
learning_rate: 5.0e-3
milestone: [700]
gamma: 0.5
batch_size: 1
num_train_epoch: 800
checkpointing_steps: 2000
validation_steps: 10

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_accumulation_steps: 1
